// lib/mockProducts.ts
export const mockProducts = [
  {
    _id: "1",
    name: "Classic Cotton T-Shirt",
    description: "Comfortable everyday t-shirt made from 100% organic cotton",
    price: 29.99,
    imageUrl:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop",
    category: "shirts",
    stock: 45,
    keywords: ["cotton", "t-shirt", "casual", "comfortable"],
    isFeatured: false,
  },
  {
    _id: "2",
    name: "Premium Denim Jeans",
    description: "Stylish dark blue denim jeans with perfect fit",
    price: 79.99,
    imageUrl:
      "https://images.unsplash.com/photo-1542272604-787c62d465d1?w=500&h=500&fit=crop",
    category: "pants",
    stock: 32,
    keywords: ["denim", "jeans", "blue", "casual"],
    isFeatured: false,
  },
  {
    _id: "3",
    name: "Running Sneakers",
    description: "Lightweight and durable running shoes for athletes",
    price: 119.99,
    imageUrl:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop",
    category: "shoes",
    stock: 28,
    keywords: ["sneakers", "running", "shoes", "athletic"],
    isFeatured: true,
  },
  {
    _id: "4",
    name: "Leather Jacket",
    description: "Premium black leather jacket for a modern look",
    price: 199.99,
    imageUrl:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500&h=500&fit=crop",
    category: "jackets",
    stock: 15,
    keywords: ["leather", "jacket", "fashion", "black"],
    isFeatured: true,
  },
  {
    _id: "5",
    name: "Formal White Shirt",
    description: "Elegant white shirt suitable for office and events",
    price: 49.99,
    imageUrl:
      "https://images.unsplash.com/photo-1603252109303-2751441dd157?w=500&h=500&fit=crop",
    category: "shirts",
    stock: 40,
    keywords: ["formal", "shirt", "office", "white"],
    isFeatured: false,
  },
  {
    _id: "6",
    name: "Cargo Pants",
    description: "Comfortable cargo pants with multiple pockets",
    price: 69.99,
    imageUrl:
      "https://images.unsplash.com/photo-1506629905607-d9d17d47e3b8?w=500&h=500&fit=crop",
    category: "pants",
    stock: 25,
    keywords: ["cargo", "pants", "casual", "outdoor"],
    isFeatured: false,
  },
  {
    _id: "7",
    name: "Sports Hoodie",
    description: "Warm and breathable hoodie for workouts and casual wear",
    price: 59.99,
    imageUrl:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500&h=500&fit=crop",
    category: "hoodies",
    stock: 35,
    keywords: ["hoodie", "sports", "warm", "casual"],
    isFeatured: true,
  },
  {
    _id: "8",
    name: "Canvas Backpack",
    description: "Durable backpack perfect for travel and daily use",
    price: 89.99,
    imageUrl:
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop",
    category: "accessories",
    stock: 20,
    keywords: ["backpack", "travel", "canvas", "bag"],
    isFeatured: false,
  },
  {
    _id: "9",
    name: "Classic Wrist Watch",
    description: "Minimalist wrist watch with premium leather strap",
    price: 149.99,
    imageUrl:
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500&h=500&fit=crop",
    category: "accessories",
    stock: 18,
    keywords: ["watch", "leather", "classic", "premium"],
    isFeatured: true,
  },
  {
    _id: "10",
    name: "Summer Shorts",
    description: "Lightweight shorts designed for maximum comfort",
    price: 34.99,
    imageUrl:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500&h=500&fit=crop",
    category: "shorts",
    stock: 50,
    keywords: ["shorts", "summer", "lightweight", "casual"],
    isFeatured: false,
  },
];